[workspace]
resolver = "2"
members = [
  # Service crates -- including crates used for accessing different services 
  # and utilities like rendering, window, audio, etc.
  "crates/service/cicada-window",
]

[workspace.package]
edition = "2021"
rust-version = "1.78.0"
